name: Pipeline
on: push
jobs:
  code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: build and install ukma:util
        run: |
          cd util
          mvn clean install
      - name: build and install ukma:model
        run: |
          cd model
          mvn clean install
      - name: Run static code analysis
        run: mvn checkstyle:check

  build:
    needs: [code-analysis]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn package
      - name: Archive JAR file
        uses: actions/upload-artifact@v4
        with:
          name: my-app-jar
          path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        run: |
          docker build -t mishatarasasenko/my-app:latest .
          docker push mishatarasasenko/my-app:latest